import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body  style={{
    backgroundImage: "url('/_04db2f22-ade1-493e-8710-7b33b7cff431.jpeg')",
    width: "100%",
    height:"100%",
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover"
  }} className={inter.className}>{children}</body>
    </html>
  );
}
